### ISSUE TITLE
Generation fails on Windows machine

### ISSUE THREAD

**Issue by kibertoad** [krakenjs/swaggerize-express#105]
When "yo swaggerize" is executed on a Windows machine, it fails after trying to execute the following (autogenerated) package.json script:

"regenerate": "yo swaggerize --only=handlers,models,tests --framework express --apiPath config\swagger.yaml"

Problematic part is the "config\swagger.yaml" - it should be "config/swagger.yaml" to work properly in Windows.

**Comment by subeeshcbabu** [comment]
The next major version of the generator fixes most of the open issues including issues in Windows platform. 
@kibertoad - Can you try the RC version '3.0.0-rc.1'  ? I will be publishing the 3.0.0 by next week if you want to wait for stable release.

**Comment by subeeshcbabu** [comment]
`generator-swaggerize@latest` - version "3.0.0" - should have fixed the windows errors.
