### ISSUE TITLE
property string dateTime format is not supported well in mocks

### ISSUE THREAD

**Issue by Kashio** [krakenjs/swaggerize-express#113]
The generated data with the generated mocks data provider for any property which is of type `string` and format `dateTime` (haven't check `date`), will result in a normal string. (e.g: taken from my spec: `start: "FcvTAQ",`)

**Comment by subeeshcbabu** [comment]
@Kashio Swagger has the format defined as `date-time`, even though the common name is `dateTime`. 

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

Please check the Mock generator module https://github.com/subeeshcbabu/swagmock for more details.
