### ISSUE TITLE
Api Path Generation Wrong in Windows

### ISSUE THREAD

**Issue by Lucg** [krakenjs/swaggerize-express#66]
Under Windows, the path generated by Swaggerize in server.js is wrong, since it returns something in the like of:

api: path.resolve('./config\swagger.json'),

Note: error in **./config\**, which should be **./config/**

The same happens in all the automated tests generated, which is a rather more serious problem

**Comment by Lucg** [comment]
The problem is related to the fact that the path is generated as a string by using path.join and the like.
On windows this results in a path that will have all the backslashes escaped:

.\\test\\api\\something.json

when used in the templates, this will turn into:

.\test\api\something.json

thus the backslashes will be considered as simple escape characters.

**Comment by tlivings** [comment]
Sounds like this issue belongs to `generator-swaggerize`.

**Comment by tlivings** [comment]
Closing now that we are tracking in generator.
