### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by h0ke** [krakenjs/swaggerize-express#72]
Is there a known way to implement CORS, especially preflight, with swaggerize-express?

Thanks!

**Comment by tlivings** [comment]
Should be able to do app.use(cors) before adding swaggerize-express. Does this not work?

**Comment by h0ke** [comment]
The `before adding swaggerize-express` part was the bit I messed up. Working now.

Thanks for the quick reply!

**Comment by tlivings** [comment]
No problem. Perhaps I should just embed cors support directly.

**Comment by aredridel** [comment]
Just say no to feature creep!

**Comment by tlivings** [comment]
:) the only reason I mention it is due to how common this need is for reading Api definitions from a swagger ui.

**Comment by aredridel** [comment]
True. Way to make a spec that incorporates ALL the cross-cutting concerns.

**Comment by h0ke** [comment]
I'm not sure embedding `cors` directly would be needed. 

Admittedly, this was a lack of experience with express middleware and the importance of `.use` order.

In retrospect, using `cors` prior to `wsaggerize-express` makes sense, but since the "magic" of `.use` is so well abstracted, the order of things isn't immediately obvious.
